name: "Bug report"
description: "Reporta un error"
labels: ["bug"]
title: "[BUG] - <título corto>"
body:
  - type: textarea
    id: expected
    attributes:
      label: "Comportamiento esperado"

  - type: textarea
    id: actual
    attributes:
      label: "Comportamiento actual"

  - type: textarea
    id: steps
    attributes:
      label: "Pasos para reproducir"
      description: "Paso a paso, incluye capturas si aplica"
