name: Desplegar Frontend a Firebase Hosting

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_and_deploy_frontend:
    name: Build y Deploy del Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Autenticar con Google Cloud (OIDC)
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.DEPLOY_SA }}

      - name: Configurar gcloud
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
      
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias del proyecto
        run: npm install

      - name: Compilar el proyecto para producción
        run: npm run build

      - name: Desplegar a Firebase Hosting
        run: firebase deploy --only hosting --project=${{ vars.GCP_PROJECT_ID }}
