name: Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options: [staging, production]
        required: true

jobs:
  call-reusable-deploy:
    uses: Arquitectura-KodeHaus/.github/.github/workflows/reusable-deploy.yml@main
    with:
      environment: ${{ inputs.env }}
